version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    # Увага: порт 3000 більше не потрібен, оскільки фронтенд тепер сервірується через Nginx
    # ports:
    #   - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    env_file:
      - ./backend/.env

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html   # Монтуємо скомпільований фронтенд
    depends_on:
      - backend
    restart: on-failure