version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - APP_PORT=5000
      - APP_HOST=0.0.0.0
      - FRONTEND_URL=http://localhost:3000
      - MONGO_URL=mongodb+srv://Nitrix:nitrix1q@cluster0.zvelh.mongodb.net/
      - MONGO_INITDB_DATABASE=express_aws
      - MONGO_INITDB_ROOT_USERNAME=Nitrix
      - MONGO_INITDB_ROOT_PASSWORD=nitrix1q
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Nitrix
      MONGO_INITDB_ROOT_PASSWORD: nitrix1q
      MONGO_INITDB_DATABASE: express_aws